/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.javafx.collections.ArrayListenerHelper;
import controller.HostelController;
import controller.RegistrationController;
import dto.HostelDTO;
import dto.RegistrationDTO;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ashen Koralage
 */
public class DashBoard extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    private int posX;   // X position of screen
    private int posY;   //Y position of screen

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
        setDate();
        setFullScreen();
        loadAllBuildings();
        getTime();
        loadAllGuests();
//        panel2.setBackground(new java.awt.Color(215, 219, 215, 125));
       

    }

    DashBoard(String admin) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblreservation = new javax.swing.JLabel();
        lblDashtime = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblhostel = new javax.swing.JLabel();
        lblroomType = new javax.swing.JLabel();
        lblfaciliti = new javax.swing.JLabel();
        lblguests = new javax.swing.JLabel();
        lblrooms = new javax.swing.JLabel();
        lblreservation1 = new javax.swing.JLabel();
        lblhostels1 = new javax.swing.JLabel();
        lblregistration1 = new javax.swing.JLabel();
        lblpayments1 = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        lblpayments = new javax.swing.JLabel();
        lblregistration = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblreservation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblreservation.setForeground(new java.awt.Color(102, 102, 102));
        lblreservation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblreservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/q2.png"))); // NOI18N
        lblreservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblreservationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblreservationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblreservationMouseExited(evt);
            }
        });
        jPanel1.add(lblreservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 80, -1));

        lblDashtime.setBackground(new java.awt.Color(255, 255, 255));
        lblDashtime.setFont(new java.awt.Font("Tempus Sans ITC", 1, 25)); // NOI18N
        lblDashtime.setText("Year-Month-Date");
        jPanel1.add(lblDashtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 340, 50));

        jLabel12.setFont(new java.awt.Font("Trajan Pro", 1, 40)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("Nugasewana");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 420, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lock.png"))); // NOI18N
        jLabel3.setText("LOGOUT");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, -1, -1));

        lblhostel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblhostel.setForeground(new java.awt.Color(102, 102, 102));
        lblhostel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hostel.png"))); // NOI18N
        lblhostel.setText("Hostel");
        lblhostel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblhostelMouseMoved(evt);
            }
        });
        lblhostel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblhostelFocusGained(evt);
            }
        });
        lblhostel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhostelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblhostelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblhostelMouseExited(evt);
            }
        });
        jPanel1.add(lblhostel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 110, -1));

        lblroomType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblroomType.setForeground(new java.awt.Color(102, 102, 102));
        lblroomType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_notes.png"))); // NOI18N
        lblroomType.setText("Room Types");
        lblroomType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblroomTypeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblroomTypeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblroomTypeMouseExited(evt);
            }
        });
        jPanel1.add(lblroomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 550, 150, -1));

        lblfaciliti.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblfaciliti.setForeground(new java.awt.Color(102, 102, 102));
        lblfaciliti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/facility.png"))); // NOI18N
        lblfaciliti.setText("Facilities");
        lblfaciliti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblfacilitiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblfacilitiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblfacilitiMouseExited(evt);
            }
        });
        jPanel1.add(lblfaciliti, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 130, 70));

        lblguests.setBackground(new java.awt.Color(204, 204, 204));
        lblguests.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblguests.setForeground(new java.awt.Color(255, 255, 255));
        lblguests.setOpaque(true);
        jPanel1.add(lblguests, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 230, 60));

        lblrooms.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblrooms.setForeground(new java.awt.Color(102, 102, 102));
        lblrooms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/room.png"))); // NOI18N
        lblrooms.setText("Rooms");
        lblrooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblroomsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblroomsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblroomsMouseExited(evt);
            }
        });
        jPanel1.add(lblrooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 540, 110, 70));

        lblreservation1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblreservation1.setForeground(new java.awt.Color(102, 102, 102));
        lblreservation1.setText("Reservation");
        jPanel1.add(lblreservation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, 130, -1));

        lblhostels1.setBackground(new java.awt.Color(204, 204, 204));
        lblhostels1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblhostels1.setForeground(new java.awt.Color(255, 255, 255));
        lblhostels1.setOpaque(true);
        jPanel1.add(lblhostels1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 230, 60));

        lblregistration1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblregistration1.setForeground(new java.awt.Color(102, 102, 102));
        lblregistration1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblregistration1.setText("Registrations");
        jPanel1.add(lblregistration1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 270, 130, -1));

        lblpayments1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblpayments1.setForeground(new java.awt.Color(102, 102, 102));
        lblpayments1.setText("Payments");
        jPanel1.add(lblpayments1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 270, 130, -1));

        lblClock.setFont(new java.awt.Font("Tempus Sans ITC", 1, 25)); // NOI18N
        lblClock.setText("time");
        jPanel1.add(lblClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 70, 290, 60));

        lblpayments.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblpayments.setForeground(new java.awt.Color(102, 102, 102));
        lblpayments.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpayments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Loan.png"))); // NOI18N
        lblpayments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblpaymentsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblpaymentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblpaymentsMouseExited(evt);
            }
        });
        jPanel1.add(lblpayments, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 200, 130, -1));

        lblregistration.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblregistration.setForeground(new java.awt.Color(102, 102, 102));
        lblregistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblregistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add%20employee.png"))); // NOI18N
        lblregistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblregistrationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblregistrationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblregistrationMouseExited(evt);
            }
        });
        jPanel1.add(lblregistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 200, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nugatree.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 760, 670));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), null, null, new java.awt.Color(153, 153, 153)));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblregistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregistrationMouseClicked
        new GuestRegistrationForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblregistrationMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       new LoginForm().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void lblreservationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblreservationMouseEntered
       lblreservation1.setForeground(Color.orange);
    }//GEN-LAST:event_lblreservationMouseEntered

    private void lblreservationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblreservationMouseExited
        lblreservation1.setForeground(Color.gray);
    }//GEN-LAST:event_lblreservationMouseExited

    private void lblregistrationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregistrationMouseEntered
       lblregistration1.setForeground(Color.orange);
    }//GEN-LAST:event_lblregistrationMouseEntered

    private void lblregistrationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregistrationMouseExited
        lblregistration1.setForeground(Color.gray);
    }//GEN-LAST:event_lblregistrationMouseExited

    private void lblpaymentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpaymentsMouseEntered
        lblpayments1.setForeground(Color.orange);
    }//GEN-LAST:event_lblpaymentsMouseEntered

    private void lblpaymentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpaymentsMouseExited
        lblpayments1.setForeground(Color.gray);
    }//GEN-LAST:event_lblpaymentsMouseExited

    private void lblreservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblreservationMouseClicked
        new ReservationForm1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblreservationMouseClicked

    private void lblfacilitiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfacilitiMouseExited
        lblfaciliti.setForeground(Color.gray);
    }//GEN-LAST:event_lblfacilitiMouseExited

    private void lblfacilitiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfacilitiMouseEntered
        lblfaciliti.setForeground(Color.orange);
    }//GEN-LAST:event_lblfacilitiMouseEntered

    private void lblfacilitiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfacilitiMouseClicked
        new FacilityForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblfacilitiMouseClicked

    private void lblhostelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhostelMouseExited
        lblhostel.setForeground(Color.gray);
    }//GEN-LAST:event_lblhostelMouseExited

    private void lblhostelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhostelMouseEntered
        lblhostel.setForeground(Color.orange);
    }//GEN-LAST:event_lblhostelMouseEntered

    private void lblhostelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhostelMouseClicked
        new HostelForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblhostelMouseClicked

    private void lblhostelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblhostelFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_lblhostelFocusGained

    private void lblhostelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhostelMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblhostelMouseMoved

    private void lblroomTypeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblroomTypeMouseExited
        lblroomType.setForeground(Color.gray);
    }//GEN-LAST:event_lblroomTypeMouseExited

    private void lblroomTypeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblroomTypeMouseEntered
        lblroomType.setForeground(Color.orange);
    }//GEN-LAST:event_lblroomTypeMouseEntered

    private void lblroomTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblroomTypeMouseClicked
        new Room_TypeForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblroomTypeMouseClicked

    private void lblroomsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblroomsMouseExited
        lblrooms.setForeground(Color.gray);
    }//GEN-LAST:event_lblroomsMouseExited

    private void lblroomsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblroomsMouseEntered
        lblrooms.setForeground(Color.orange);
    }//GEN-LAST:event_lblroomsMouseEntered

    private void lblroomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblroomsMouseClicked
        new RoomForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblroomsMouseClicked

    private void lblpaymentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpaymentsMouseClicked
        new PaymentForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblpaymentsMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DashBoard().setVisible(true);
//            }
//        });
//        
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblDashtime;
    private javax.swing.JLabel lblfaciliti;
    private javax.swing.JLabel lblguests;
    private javax.swing.JLabel lblhostel;
    private javax.swing.JLabel lblhostels1;
    private javax.swing.JLabel lblpayments;
    private javax.swing.JLabel lblpayments1;
    private javax.swing.JLabel lblregistration;
    private javax.swing.JLabel lblregistration1;
    private javax.swing.JLabel lblreservation;
    private javax.swing.JLabel lblreservation1;
    private javax.swing.JLabel lblroomType;
    private javax.swing.JLabel lblrooms;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        lblDashtime.setText(LocalDate.now().toString());
    }

    private void setFullScreen() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize.width, screenSize.height);

        Component component = this;
        component.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                posX = e.getX();
                posY = e.getY();
            }
        });

        component.addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent evt) {
                Rectangle rectangle = getBounds();
                setBounds(evt.getXOnScreen() - posX, evt.getYOnScreen() - posY,
                        rectangle.width, rectangle.height);
            }
        });
    }

    private void getTime() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Date curDate = new Date();
                    SimpleDateFormat dateFormat= new SimpleDateFormat("HH:mm:ss aa");
                    String currentTime = dateFormat.format(curDate);

                    lblClock.setText(currentTime);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {

                    }
                }
            }
        }).start();
    }

    private void loadAllBuildings() {
        try {
            int count=0;
            ArrayList<HostelDTO>all=HostelController.getAllHostels();
            for (HostelDTO hostels : all) {
                count++;
                lblhostels1.setText(count+"..Hostels ");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllGuests() {
        try {
            int count=0;
            ArrayList<RegistrationDTO>all=RegistrationController.getAllGuests();
            for (RegistrationDTO guests : all) {
                count++;
                lblguests.setText(count+"..Guests ");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
