/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.HostelController;
import controller.RoomController;
import dto.HostelDTO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.IdGenerator;
import util.Validation;

/**
 *
 * @author Ashen Koralage
 */
public class HostelForm extends javax.swing.JFrame {

    private DefaultTableModel dtm;

    /**
     * Creates new form Hostel
     */
    public HostelForm() {
        initComponents();
//        dtm = (DefaultTableModel) tblHostel.getModel();
//        getAllHostels();
//        loadAllBuildings();
        setIdAuto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txthostelID = new javax.swing.JTextField();
        txtRooms = new javax.swing.JTextField();
        txtgenderResi = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTP2 = new javax.swing.JTextField();
        btnSave1 = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnupdate1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Trajan Pro", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("Nugasewana");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 200, 40));

        txthostelID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txthostelIDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txthostelIDMouseEntered(evt);
            }
        });
        txthostelID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthostelIDActionPerformed(evt);
            }
        });
        txthostelID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txthostelIDKeyPressed(evt);
            }
        });
        jPanel2.add(txthostelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 470, 30));

        txtRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomsActionPerformed(evt);
            }
        });
        txtRooms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRoomsKeyReleased(evt);
            }
        });
        jPanel2.add(txtRooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 450, 30));

        txtgenderResi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenderResiActionPerformed(evt);
            }
        });
        txtgenderResi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtgenderResiKeyReleased(evt);
            }
        });
        jPanel2.add(txtgenderResi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 470, 30));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddressKeyReleased(evt);
            }
        });
        jPanel2.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 470, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_1.png"))); // NOI18N
        jLabel7.setText("Home");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, -50, 110, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Hostel Building");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 310, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Room Count");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 220, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Gender Of Residence");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 170, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Telephone No");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 170, -1));

        txtTP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTP2ActionPerformed(evt);
            }
        });
        txtTP2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTP2KeyReleased(evt);
            }
        });
        jPanel2.add(txtTP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 450, 30));

        btnSave1.setBackground(new java.awt.Color(0, 0, 255));
        btnSave1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/accept.png"))); // NOI18N
        btnSave1.setText("Save");
        btnSave1.setContentAreaFilled(false);
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 500, 120, 40));

        btndelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btndelete.setText("Remove");
        btndelete.setContentAreaFilled(false);
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 550, 140, 30));

        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnsearch.setContentAreaFilled(false);
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 60, 30));

        btnupdate1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/page_edit.png"))); // NOI18N
        btnupdate1.setText("Update");
        btnupdate1.setContentAreaFilled(false);
        btnupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdate1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnupdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 600, 130, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Hostel Number");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 120, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Address");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 170, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_1.png"))); // NOI18N
        jLabel15.setText("Home");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 80, 40));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 760));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gray background.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        try {
            String HID = txthostelID.getText();
            String rooms = txtRooms.getText();
            String Address = txtAddress.getText();
            String genderResi = txtgenderResi.getText();
            String Tp = txtAddress.getText();

            HostelDTO hosModel = new HostelDTO(HID, rooms, genderResi, Tp, Address);
            boolean addHostel = HostelController.addHostel(hosModel);
            if (addHostel) {
                JOptionPane.showMessageDialog(this, "Hostel Save Successfully");
//                getAllHostels();
                clearAll();

            } else {
                JOptionPane.showMessageDialog(this, "Failed!");
                clearAll();
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSave1ActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed

        try {
            String hostelID = txthostelID.getText();
            boolean deleteHostel = deleteHostel(hostelID);
            if (deleteHostel) {
                JOptionPane.showMessageDialog(this, "Successfully Deleted");
//                getAllHostels();
                clearAll();
            } else {
                JOptionPane.showMessageDialog(this, "Faild!\n Please Check Once Again");
                clearAll();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        try {
            //  LoadAllHostels();
            String searchId = txthostelID.getText();
            HostelDTO searchHostel = HostelController.searchHostel(searchId);
            if (searchHostel != null) {
                txthostelID.setText(searchHostel.getHID());
                txtRooms.setText(searchHostel.getNo_of_Rooms());
                txtgenderResi.setText(searchHostel.getGender_of_residence());
                txtAddress.setText(searchHostel.getAddress());
                txtTP2.setText(searchHostel.getPhone_Number());
            } else {
                clearAll();
                JOptionPane.showMessageDialog(this, "No Such Hostel For ID" + searchId);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void txthostelIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txthostelIDMouseClicked

    }//GEN-LAST:event_txthostelIDMouseClicked

    private void txthostelIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthostelIDKeyPressed

    }//GEN-LAST:event_txthostelIDKeyPressed

    private void txthostelIDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txthostelIDMouseEntered

    }//GEN-LAST:event_txthostelIDMouseEntered

    private void txthostelIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthostelIDActionPerformed
        txtgenderResi.requestFocus();
    }//GEN-LAST:event_txthostelIDActionPerformed

    private void txtRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomsActionPerformed
        txtTP2.requestFocus();
    }//GEN-LAST:event_txtRoomsActionPerformed

    private void txtgenderResiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenderResiActionPerformed

        txtAddress.requestFocus();
    }//GEN-LAST:event_txtgenderResiActionPerformed

    private void txtTP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTP2ActionPerformed
        btnSave1.requestFocus();
        btnSave1.doClick();
    }//GEN-LAST:event_txtTP2ActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        txtRooms.requestFocus();
    }//GEN-LAST:event_txtAddressActionPerformed

    private void btnupdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdate1ActionPerformed
        try {
            String HID = txthostelID.getText();
            String rooms = txtRooms.getText();
            String genderResi = txtgenderResi.getText();
            String Address = txtAddress.getText();
            String Tp = txtTP2.getText();

            HostelDTO hostelDTO = new HostelDTO(HID, rooms, genderResi, Address, Tp);
            boolean updateHostel = HostelController.updateHostel(hostelDTO);
            if (updateHostel) {
                JOptionPane.showMessageDialog(this, "Successfully Updated");
//                getAllHostels();
                clearAll();
            } else {
                JOptionPane.showMessageDialog(this, "Faild!");
                clearAll();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnupdate1ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        new DashBoard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void txtRoomsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRoomsKeyReleased
        Validation.numberOnly(txtRooms);
    }//GEN-LAST:event_txtRoomsKeyReleased

    private void txtTP2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTP2KeyReleased
        Validation.phoneNumber(txtTP2, evt);
    }//GEN-LAST:event_txtTP2KeyReleased

    private void txtAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyReleased
        Validation.name(txtAddress);
    }//GEN-LAST:event_txtAddressKeyReleased

    private void txtgenderResiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgenderResiKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenderResiKeyReleased

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        new DashBoard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HostelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HostelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HostelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HostelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HostelForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtRooms;
    private javax.swing.JTextField txtTP2;
    private javax.swing.JTextField txtgenderResi;
    private javax.swing.JTextField txthostelID;
    // End of variables declaration//GEN-END:variables

//    private void getAllHostels() {
//        try {
//            dtm.setRowCount(0);
//            ArrayList<HostelDTO> allHostel = HostelController.getAllHostels();
//            for (HostelDTO hos : allHostel) {
//                Object[] rowdata = {hos.getHID(), hos.getNo_of_Rooms(), hos.getGender_of_residence(), hos.getPhone_Number(), hos.getAddress()};
//                dtm.addRow(rowdata);
//            }
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(HostelForm.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(HostelForm.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    private void clearAll() {
        txthostelID.setText("");
        txtgenderResi.setText("");
        txtRooms.setText("");
        txtAddress.setText("");
        txtTP2.setText("");
    }

    private boolean deleteHostel(String hostelID) throws SQLException, ClassNotFoundException {
        return HostelController.deleteHostel(hostelID);
    }

    private void LoadAllHostels() {
        txthostelID.removeAll();
        try {

            ArrayList<HostelDTO> allhostels = HostelController.getAllHostels();
            for (HostelDTO all : allhostels) {
                txthostelID.setText(all.getHID());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HostelForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HostelForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setIdAuto() {
        try {
            String newId = IdGenerator.getNewId("hostel", "HID", "H");
            txthostelID.setText(newId);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GuestRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GuestRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
