/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.KeyMoneyController;
import controller.MonthlyPaymentController;
import dto.KeyMoneyDTO;
import dto.MonthlyPaymentDTO;
import entity.MonthlyPayment;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import util.DateChooser;
import util.IdGenerator;
import util.Validation;

/**
 *
 * @author Ashen Koralage
 */
public class PaymentForm extends javax.swing.JFrame {

    /**
     * Creates new form Key_MoneyForm
     */
    private String guestId;
    private String booking;
    private String keyMoney;

    public PaymentForm() {
        initComponents();
        setAutoID();
        setAutoMPID();
    }

    PaymentForm(String guestId, String booking, String keyMoney) {
        initComponents();
        this.guestId = guestId;
        this.keyMoney = keyMoney;
        this.booking = booking;
        txtgid1.setText(guestId);
        txtpaiddate1.setText(booking);
        txtamount1.setText(keyMoney);
        setAutoID();
        setAutoMPID();

    }

    /*
   think you have  customer form and you want to send data to item form
then itemform is the place that you want to send the data from customer form
    ===========
    therefore call the item form constructor and pass your data as you need
like this
this is customer form
new ItemForm(include parameters as you want):
    then make a constructor for item form in the item form too
that's it
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtpaymentId = new javax.swing.JTextField();
        txtguestID = new javax.swing.JTextField();
        txtamount = new javax.swing.JTextField();
        txtnextdate = new com.toedter.calendar.JDateChooser();
        txtpaymentDate = new com.toedter.calendar.JDateChooser();
        btnMpay = new javax.swing.JButton();
        lblsearchkeyMoney1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtkId1 = new javax.swing.JTextField();
        txtgid1 = new javax.swing.JTextField();
        txtpaiddate1 = new javax.swing.JTextField();
        txtamount1 = new javax.swing.JTextField();
        btnpay1 = new javax.swing.JButton();
        txtpayback1 = new com.toedter.calendar.JDateChooser();
        lblsearchkeyMoney = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Payments");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 240, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_1.png"))); // NOI18N
        jLabel5.setText("Home");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 110, 40));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 60));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Next payment date");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, 29));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Payment ID");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, 29));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Guest ID");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 29));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Amount");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 29));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Payment Date");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, 29));

        txtpaymentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaymentIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtpaymentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 300, 30));

        txtguestID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtguestIDActionPerformed(evt);
            }
        });
        jPanel2.add(txtguestID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 300, 30));

        txtamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtamountKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtamountKeyReleased(evt);
            }
        });
        jPanel2.add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 300, 30));
        jPanel2.add(txtnextdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 300, 30));
        jPanel2.add(txtpaymentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 300, 30));

        btnMpay.setBackground(new java.awt.Color(51, 255, 0));
        btnMpay.setText("Pay");
        btnMpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMpayActionPerformed(evt);
            }
        });
        jPanel2.add(btnMpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 283, 60, 20));

        lblsearchkeyMoney1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        lblsearchkeyMoney1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsearchkeyMoney1MouseClicked(evt);
            }
        });
        jPanel2.add(lblsearchkeyMoney1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 40, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 550, 420));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Monthly paymets");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, -1, 30));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Guest ID");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 96, 89, 27));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Paid Date");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 139, 89, 27));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Amount");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 89, 27));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Pay back date");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 110, 27));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Key Money ID");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, 29));

        txtkId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkId1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtkId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 300, 30));

        txtgid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgid1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtgid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 300, 30));

        txtpaiddate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaiddate1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtpaiddate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 300, 30));

        txtamount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtamount1ActionPerformed(evt);
            }
        });
        txtamount1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtamount1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtamount1KeyReleased(evt);
            }
        });
        jPanel3.add(txtamount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 300, 30));

        btnpay1.setBackground(new java.awt.Color(0, 255, 0));
        btnpay1.setText("Pay");
        btnpay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpay1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnpay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 60, 20));
        jPanel3.add(txtpayback1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 220, 300, 30));

        lblsearchkeyMoney.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        lblsearchkeyMoney.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsearchkeyMoneyMouseClicked(evt);
            }
        });
        jPanel3.add(lblsearchkeyMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 40, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 550, 420));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Key Money");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1378, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMpayActionPerformed
        try {
            String pid = txtpaymentId.getText();
            String gid = txtguestID.getText();
            String amount = txtamount.getText();
            String paymentDate = DateChooser.getDate(txtpaymentDate);
            String nextDate = DateChooser.getDate(txtnextdate);
            MonthlyPaymentDTO monthModel = new MonthlyPaymentDTO(pid, gid, amount, paymentDate, nextDate);
            boolean addpayment = MonthlyPaymentController.addpayment(monthModel);
            if (addpayment) {
//                InputStream is = this.getClass().getResourceAsStream("Blank_A4.jasper");
//                HashMap paraValues= new HashMap();
//                paraValues.put("mpid", pid);
//                paraValues.put("GID", gid);
//                paraValues.put("Amount", amount);
//                paraValues.put("payment_date", paymentDate);
//                paraValues.put("nextPaymentDate", nextDate);
                
               // JasperFillManager fillReport = JasperFillManager.fillReport(is, paraValues, MonthlyPayment);
                JOptionPane.showMessageDialog(this, "Successfully Paid");
                clearAllPayments();
            } else {
                JOptionPane.showMessageDialog(this, "Failed To Pay");
                clearAllPayments();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMpayActionPerformed

    private void lblsearchkeyMoney1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsearchkeyMoney1MouseClicked
        try {
            String gid = txtguestID.getText();
            MonthlyPaymentDTO searchPayment = MonthlyPaymentController.searchPayment(gid);
            if (searchPayment != null) {
                txtpaymentId.setText(searchPayment.getMpid());
                txtguestID.setText(searchPayment.getGid());
                txtamount.setText(searchPayment.getAmount());
                DateChooser.setDefaultDate(txtpaymentDate);
                DateChooser.setDefaultDate(txtnextdate);
            } else {
                clearAllPayments();
                JOptionPane.showMessageDialog(this, "No any Payments For Guest ID :" + gid);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblsearchkeyMoney1MouseClicked

    private void txtpaymentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaymentIdActionPerformed
        txtguestID.requestFocus();
    }//GEN-LAST:event_txtpaymentIdActionPerformed

    private void txtguestIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtguestIDActionPerformed
        txtamount.requestFocus();
    }//GEN-LAST:event_txtguestIDActionPerformed

    private void txtamountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtamountKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamountKeyPressed

    private void txtamountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtamountKeyReleased
        Validation.numberOnly(txtamount);
    }//GEN-LAST:event_txtamountKeyReleased

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        new DashBoard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void lblsearchkeyMoneyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsearchkeyMoneyMouseClicked
        try {
            String gid = txtgid1.getText();
            KeyMoneyDTO searchKeyMoney = KeyMoneyController.searchPayment(gid);
            if (searchKeyMoney != null) {
                txtkId1.setText(searchKeyMoney.getkID());
                txtgid1.setText(searchKeyMoney.getGid());
                txtpaiddate1.setText(searchKeyMoney.getPaidDate());
                txtamount1.setText(searchKeyMoney.getAmount());
                DateChooser.setDefaultDate(txtpayback1);
            } else {
                clearAll();
                JOptionPane.showMessageDialog(this, "No Any Guests Above ID" + gid);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblsearchkeyMoneyMouseClicked

    private void btnpay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpay1ActionPerformed
        try {
            String kid = txtkId1.getText();
            String gid = txtgid1.getText();
            String paidDate = txtpaiddate1.getText();
            String amount = txtamount1.getText();
            String payBack = DateChooser.getDate(txtpayback1);
            KeyMoneyDTO payModel = new KeyMoneyDTO(kid, gid, paidDate, amount, payBack);
            boolean addPayment = KeyMoneyController.addPayment(payModel);
            if (addPayment) {
                JOptionPane.showMessageDialog(this, "Successfully Paid");
                clearAll();
            } else {
                JOptionPane.showMessageDialog(this, "Failed To Pay");
                clearAll();

            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnpay1ActionPerformed

    private void txtamount1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtamount1KeyReleased
        Validation.numberOnly(txtamount1);
    }//GEN-LAST:event_txtamount1KeyReleased

    private void txtamount1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtamount1KeyPressed

    }//GEN-LAST:event_txtamount1KeyPressed

    private void txtamount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtamount1ActionPerformed
        txtpayback1.requestFocus();
    }//GEN-LAST:event_txtamount1ActionPerformed

    private void txtpaiddate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaiddate1ActionPerformed
        txtamount1.requestFocus();
    }//GEN-LAST:event_txtpaiddate1ActionPerformed

    private void txtgid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgid1ActionPerformed
        txtpaiddate1.requestFocus();
    }//GEN-LAST:event_txtgid1ActionPerformed

    private void txtkId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkId1ActionPerformed
        txtgid1.requestFocus();
    }//GEN-LAST:event_txtkId1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PaymentForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMpay;
    private javax.swing.JButton btnpay1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblsearchkeyMoney;
    private javax.swing.JLabel lblsearchkeyMoney1;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtamount1;
    private javax.swing.JTextField txtgid1;
    private javax.swing.JTextField txtguestID;
    private javax.swing.JTextField txtkId1;
    private com.toedter.calendar.JDateChooser txtnextdate;
    private javax.swing.JTextField txtpaiddate1;
    private com.toedter.calendar.JDateChooser txtpayback1;
    private com.toedter.calendar.JDateChooser txtpaymentDate;
    private javax.swing.JTextField txtpaymentId;
    // End of variables declaration//GEN-END:variables

    private void setAutoID() {
        try {
            String newId = IdGenerator.getNewId("key_Money", "KID", "K");
            txtkId1.setText(newId);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GuestRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GuestRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearAll() {
        txtamount1.setText("");
        txtgid1.setText("");
        txtkId1.setText("");
        txtpaiddate1.setText("");

    }

    private void clearAllPayments() {
        txtamount.setText("");
        txtguestID.setText("");
        txtpaymentId.setText("");

    }

    private void setAutoMPID() {
        try {
            String newId = IdGenerator.getNewId("monthly_Payment", "mpid", "P");
            txtpaymentId.setText(newId);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GuestRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GuestRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean deleteKeyMoney(String gid) throws ClassNotFoundException, SQLException {
        return KeyMoneyController.deleteKeyMoney(gid);
    }

}
